#include "src/game/envfx_snow.h"

const GeoLayout point_balloon_balloon_geo[] = {
	GEO_DISPLAY_LIST(LAYER_OPAQUE, point_balloon_Balloons_mesh_layer_1_before),
	GEO_SWITCH_CASE(6, geo_switch_bparam2),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_point_balloon_balloon_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_point_balloon_balloon_10),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_point_balloon_balloon_25),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_point_balloon_balloon_50),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_point_balloon_balloon_100),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_point_balloon_balloon_red),
	GEO_CLOSE_NODE(),
	GEO_DISPLAY_LIST(LAYER_OPAQUE, point_balloon_Balloons_mesh_layer_1_after),
	GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, point_balloon_Balloons_mesh_layer_5_before),
	GEO_SWITCH_CASE(6, geo_switch_bparam2),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, mat_point_balloon_balloon_5_decal),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, mat_point_balloon_balloon_10_decal),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, mat_point_balloon_balloon_25_decal),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, mat_point_balloon_balloon_50_decal),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, mat_point_balloon_balloon_100_decal),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, mat_point_balloon_balloon_red_decal),
	GEO_CLOSE_NODE(),
	GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, point_balloon_Balloons_mesh_layer_5_after),
	GEO_RETURN(),
};

const GeoLayout point_balloon_geo[] = {
	GEO_SWITCH_CASE(2, geo_switch_console),
	GEO_OPEN_NODE(),
		GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, point_balloon_balloon_geo),
		GEO_CLOSE_NODE(),
		GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0xB4, 200),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, point_balloon_balloon_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
