#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_A_Menu_backdrop_a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_A_Menu_backdrop_b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_A_Menu_backdrop_c_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_B_Menu_checkers_a_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_B_Menu_checkers_b_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_grounds_dl_B_Menu_checkers_c_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_C_Menu_decoration_a_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_C_Menu_decoration_b_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, castle_grounds_dl_C_Menu_decoration_c_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_D_Menu_stage_backdrops_a_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_D_Menu_stage_backdrops_b_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_grounds_dl_D_Menu_stage_backdrops_c_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_E_Menu_slots_a_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_E_Menu_slots_b_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_E_Menu_slots_c_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_F_Menu_icons_a_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_F_Menu_icons_b_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_F_Menu_icons_c_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_G_Menu_text_a_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_G_Menu_text_b_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 30, castle_grounds_dl_G_Menu_text_c_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x1987),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_NONE, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
