#include "src/game/envfx_snow.h"

const GeoLayout ccm_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(4, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, ccm_dl_1_area2_geo),
			GEO_BRANCH(1, ccm_dl_2_area2_geo),
			GEO_BRANCH(1, ccm_dl_3_area2_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_dl_1_area2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_a1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_A_wormhole_a1_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_a2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_a3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_a4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_A_wormhole_a4_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 50000, 6707, -24956, ccm_dl_A_wormhole_a4_001_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_A_wormhole_a4_001_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -20002, 1040, -17199, ccm_dl_B_platforms_a_a2_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -20050, -8399, 9180, ccm_dl_B_platforms_b_a_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 50000, 5092, -26842, ccm_dl_B_platforms_b_a_001_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -20000, -5477, -2670, ccm_dl_COL_a2_death_a1_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_dl_2_area2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_b1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_b2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_b3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_b4_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, -6253, 29, 0, -180, 0, ccm_dl_COL_a2_death_a2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_dl_3_area2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_c1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_A_wormhole_c1_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_c2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_c3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ccm_dl_A_wormhole_c4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ccm_dl_A_wormhole_c4_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 20000, -6253, 29, 0, -180, 0, ccm_dl_COL_a2_death_a3_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 127, 65535, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, -70000, 0, 0, -70000, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
