extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_dl_1_area1_geo[];
extern const GeoLayout ccm_dl_2_area1_geo[];
extern const GeoLayout ccm_dl_3_area1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const u8 ccm_area_1_collision_rooms[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_dl_1_area2_geo[];
extern const GeoLayout ccm_dl_2_area2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const u8 ccm_area_2_collision_rooms[];
extern const MacroObject ccm_area_2_macro_objs[];
extern const GeoLayout ccm_area_3_geo[];
extern const GeoLayout ccm_dl_1_area3_geo[];
extern const GeoLayout ccm_area_3[];
extern const Collision ccm_area_3_collision[];
extern const u8 ccm_area_3_collision_rooms[];
extern const MacroObject ccm_area_3_macro_objs[];
extern const GeoLayout ccm_area_4_geo[];
extern const GeoLayout ccm_dl_1_area4_geo[];
extern const GeoLayout ccm_dl_2_area4_geo[];
extern const GeoLayout ccm_area_4[];
extern const Collision ccm_area_4_collision[];
extern const u8 ccm_area_4_collision_rooms[];
extern const MacroObject ccm_area_4_macro_objs[];
extern u8 ccm_dl_galaxy_ia4_i4[];
extern u8 ccm_dl_purple_road_rgba16[];
extern u8 ccm_dl_star_floor_full_i4[];
extern u8 ccm_dl_blue_road_rgba16[];
extern u8 ccm_dl_star_tile_full_i4[];
extern u8 ccm_dl_glass_star_tiles_ia8[];
extern u8 ccm_dl_gold_ci8[];
extern u8 ccm_dl_gold_pal_rgba16[];
extern u8 ccm_dl_rainbow_ci8[];
extern u8 ccm_dl_rainbow_pal_rgba16[];
extern u8 ccm_dl_bulding_fade_a_rgba16[];
extern u8 ccm_dl_star_window_rgba16[];
extern u8 ccm_dl_bulding_fade_b_rgba16[];
extern u8 ccm_dl_bulding_fade_c_rgba16[];
extern u8 ccm_dl_bulding_fade_e_rgba16[];
extern u8 ccm_dl_bulding_fade_d_rgba16[];
extern Vtx ccm_dl_A_Galaxy_a_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Galaxy_a_mesh_layer_1_vtx_0[61];
extern Gfx ccm_dl_A_Galaxy_a_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Galaxy_b_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Galaxy_b_mesh_layer_1_vtx_0[61];
extern Gfx ccm_dl_A_Galaxy_b_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Galaxy_c_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Galaxy_c_mesh_layer_1_vtx_0[61];
extern Gfx ccm_dl_A_Galaxy_c_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Galaxy_d_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Galaxy_d_mesh_layer_1_vtx_0[61];
extern Gfx ccm_dl_A_Galaxy_d_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Galaxy_e_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Galaxy_e_mesh_layer_1_vtx_0[61];
extern Gfx ccm_dl_A_Galaxy_e_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_0[248];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_1[480];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_2[20];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_3[5249];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_A_Road_mesh_layer_5_vtx_cull[8];
extern Vtx ccm_dl_A_Road_mesh_layer_5_vtx_0[20];
extern Gfx ccm_dl_A_Road_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_1_vtx_0[100];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_1_vtx_1[134];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_1_vtx_2[132];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_1_vtx_3[100];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_1_vtx_4[64];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_1_tri_4[];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_B_buildings_a_mesh_layer_4_vtx_0[264];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_4_tri_0[];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_1_vtx_0[62];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_1_vtx_1[66];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_1_vtx_2[48];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_1_vtx_3[32];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_1_vtx_4[36];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_1_tri_4[];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_B_buildings_b_mesh_layer_4_vtx_0[244];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_4_tri_0[];
extern Vtx ccm_dl_C_railings_a_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_C_railings_a_mesh_layer_1_vtx_0[171];
extern Gfx ccm_dl_C_railings_a_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_C_railings_b_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_C_railings_b_mesh_layer_1_vtx_0[258];
extern Gfx ccm_dl_C_railings_b_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_C_railings_c_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_C_railings_c_mesh_layer_1_vtx_0[172];
extern Gfx ccm_dl_C_railings_c_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_C_railings_d_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_C_railings_d_mesh_layer_1_vtx_0[258];
extern Gfx ccm_dl_C_railings_d_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_Galaxy[];
extern Gfx mat_revert_ccm_dl_Galaxy[];
extern Gfx mat_ccm_dl_Starry_floor_layer1[];
extern Gfx mat_revert_ccm_dl_Starry_floor_layer1[];
extern Gfx mat_ccm_dl_Starry_tiles_layer1[];
extern Gfx mat_revert_ccm_dl_Starry_tiles_layer1[];
extern Gfx mat_ccm_dl_Glass_star_tiles[];
extern Gfx mat_ccm_dl_Gold[];
extern Gfx mat_revert_ccm_dl_Gold[];
extern Gfx mat_ccm_dl_Rainbow[];
extern Gfx mat_revert_ccm_dl_Rainbow[];
extern Gfx mat_ccm_dl_Bulding_a[];
extern Gfx mat_ccm_dl_Star_window[];
extern Gfx mat_ccm_dl_Bulding_b[];
extern Gfx mat_ccm_dl_Bulding_c[];
extern Gfx mat_ccm_dl_Bulding_e[];
extern Gfx mat_ccm_dl_Bulding_d[];
extern Gfx ccm_dl_A_Galaxy_a_mesh_layer_1[];
extern Gfx ccm_dl_A_Galaxy_b_mesh_layer_1[];
extern Gfx ccm_dl_A_Galaxy_c_mesh_layer_1[];
extern Gfx ccm_dl_A_Galaxy_d_mesh_layer_1[];
extern Gfx ccm_dl_A_Galaxy_e_mesh_layer_1[];
extern Gfx ccm_dl_A_Road_mesh_layer_1[];
extern Gfx ccm_dl_A_Road_mesh_layer_5[];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_1[];
extern Gfx ccm_dl_B_buildings_a_mesh_layer_4[];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_1[];
extern Gfx ccm_dl_B_buildings_b_mesh_layer_4[];
extern Gfx ccm_dl_C_railings_a_mesh_layer_1[];
extern Gfx ccm_dl_C_railings_b_mesh_layer_1[];
extern Gfx ccm_dl_C_railings_c_mesh_layer_1[];
extern Gfx ccm_dl_C_railings_d_mesh_layer_1[];
