extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_dl_1_area1_geo[];
extern const GeoLayout ccm_dl_2_area1_geo[];
extern const GeoLayout ccm_dl_3_area1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const u8 ccm_area_1_collision_rooms[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_dl_1_area2_geo[];
extern const GeoLayout ccm_dl_2_area2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const u8 ccm_area_2_collision_rooms[];
extern const MacroObject ccm_area_2_macro_objs[];
extern const GeoLayout ccm_area_3_geo[];
extern const GeoLayout ccm_dl_1_area3_geo[];
extern const GeoLayout ccm_area_3[];
extern const Collision ccm_area_3_collision[];
extern const u8 ccm_area_3_collision_rooms[];
extern const MacroObject ccm_area_3_macro_objs[];
extern const GeoLayout ccm_area_4_geo[];
extern const GeoLayout ccm_dl_1_area4_geo[];
extern const GeoLayout ccm_dl_2_area4_geo[];
extern const GeoLayout ccm_area_4[];
extern const Collision ccm_area_4_collision[];
extern const u8 ccm_area_4_collision_rooms[];
extern const MacroObject ccm_area_4_macro_objs[];
extern u8 ccm_dl_rainbow_ci8[];
extern u8 ccm_dl_rainbow_pal_rgba16[];
extern u8 ccm_dl_purple_road_rgba16[];
extern u8 ccm_dl_star_floor_i4[];
extern u8 ccm_dl_glass_star_tiles_ia8[];
extern u8 ccm_dl_gold_ci8[];
extern u8 ccm_dl_gold_pal_rgba16[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_0[5249];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_1[687];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_A_Road_mesh_layer_1_vtx_2[20];
extern Gfx ccm_dl_A_Road_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_A_Road_mesh_layer_5_vtx_cull[8];
extern Vtx ccm_dl_A_Road_mesh_layer_5_vtx_0[40];
extern Gfx ccm_dl_A_Road_mesh_layer_5_tri_0[];
extern Gfx mat_ccm_dl_Rainbow[];
extern Gfx mat_revert_ccm_dl_Rainbow[];
extern Gfx mat_ccm_dl_Starry_floor_layer1[];
extern Gfx mat_revert_ccm_dl_Starry_floor_layer1[];
extern Gfx mat_ccm_dl_Glass_star_tiles[];
extern Gfx mat_ccm_dl_Gold[];
extern Gfx mat_revert_ccm_dl_Gold[];
extern Gfx ccm_dl_A_Road_mesh_layer_1[];
extern Gfx ccm_dl_A_Road_mesh_layer_5[];
