extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern u8 bob_dl_day_3_0_rgba16[];
extern u8 bob_dl_sun_ia8[];
extern u8 bob_dl_snow_small_sparkles_ci8[];
extern u8 bob_dl_snow_small_sparkles_x_snow_small_pal_rgba16[];
extern u8 bob_dl_snow_small_ci8[];
extern u8 bob_dl_rocks_large_i4[];
extern u8 bob_dl_mountain_i8[];
extern Vtx bob_dl_0_SKY_DOME_mesh_layer_1_vtx_0[670];
extern Gfx bob_dl_0_SKY_DOME_mesh_layer_1_tri_0[];
extern Vtx bob_dl_0_SKY_SUN_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_0_SKY_SUN_mesh_layer_5_tri_0[];
extern Vtx bob_dl_A_area1_slide_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_A_area1_slide_mesh_layer_1_vtx_0[2371];
extern Gfx bob_dl_A_area1_slide_mesh_layer_1_tri_0[];
extern Vtx bob_dl_A_area1_slide_mesh_layer_1_vtx_1[1024];
extern Gfx bob_dl_A_area1_slide_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_day_3_0[];
extern Gfx mat_revert_bob_dl_day_3_0[];
extern Gfx mat_bob_dl_Sun[];
extern Gfx mat_revert_bob_dl_Sun[];
extern Gfx mat_bob_dl_Snow_layer1[];
extern Gfx mat_revert_bob_dl_Snow_layer1[];
extern Gfx mat_bob_dl_Rock_layer1[];
extern Gfx mat_revert_bob_dl_Rock_layer1[];
extern Gfx bob_dl_0_SKY_DOME_mesh_layer_1[];
extern Gfx bob_dl_0_SKY_SUN_mesh_layer_5[];
extern Gfx bob_dl_A_area1_slide_mesh_layer_1[];
