extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern u8 hmc_dl_mountain_fixed_i8[];
extern Vtx hmc_dl_COL_floor_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_COL_floor_mesh_layer_1_vtx_0[8];
extern Gfx hmc_dl_COL_floor_mesh_layer_1_tri_0[];
extern Gfx mat_hmc_dl_COL_GROUND2[];
extern Gfx mat_revert_hmc_dl_COL_GROUND2[];
extern Gfx hmc_dl_COL_floor_mesh_layer_1[];
