extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern const GeoLayout hmc_area_2_geo[];
extern const GeoLayout hmc_area_2[];
extern const Collision hmc_area_2_collision[];
extern const MacroObject hmc_area_2_macro_objs[];
extern const GeoLayout hmc_area_3_geo[];
extern const GeoLayout hmc_area_3[];
extern const Collision hmc_area_3_collision[];
extern const MacroObject hmc_area_3_macro_objs[];
extern const GeoLayout hmc_area_4_geo[];
extern const GeoLayout hmc_area_4[];
extern const Collision hmc_area_4_collision[];
extern const MacroObject hmc_area_4_macro_objs[];
extern u8 hmc_dl_mountain_fixed_i8[];
extern Vtx hmc_dl_BALLS_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_BALLS_mesh_layer_1_vtx_0[952];
extern Gfx hmc_dl_BALLS_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor_1_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_COL_floor_1_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_COL_floor_1_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor_1_mesh_layer_1_vtx_1[4];
extern Gfx hmc_dl_COL_floor_1_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_BALLS_001_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_BALLS_001_mesh_layer_1_vtx_0[952];
extern Gfx hmc_dl_BALLS_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor2_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_COL_floor2_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_COL_floor2_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor2_mesh_layer_1_vtx_1[4];
extern Gfx hmc_dl_COL_floor2_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_COL_floor2_mesh_layer_1_vtx_2[4];
extern Gfx hmc_dl_COL_floor2_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_BALLS_002_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_BALLS_002_mesh_layer_1_vtx_0[952];
extern Gfx hmc_dl_BALLS_002_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor3_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_COL_floor3_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_COL_floor3_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor3_mesh_layer_1_vtx_1[4];
extern Gfx hmc_dl_COL_floor3_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_COL_floor3_mesh_layer_1_vtx_2[4];
extern Gfx hmc_dl_COL_floor3_mesh_layer_1_tri_2[];
extern Vtx hmc_dl_BALLS_003_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_BALLS_003_mesh_layer_1_vtx_0[952];
extern Gfx hmc_dl_BALLS_003_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor4_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_COL_floor4_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_COL_floor4_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_COL_floor4_mesh_layer_1_vtx_1[4];
extern Gfx hmc_dl_COL_floor4_mesh_layer_1_tri_1[];
extern Gfx mat_hmc_dl_COL_GROUND2[];
extern Gfx mat_hmc_dl_COL_INSTA[];
extern Gfx mat_hmc_dl_COL_INSTA2[];
extern Gfx hmc_dl_BALLS_mesh_layer_1[];
extern Gfx hmc_dl_COL_floor_1_mesh_layer_1[];
extern Gfx hmc_dl_BALLS_001_mesh_layer_1[];
extern Gfx hmc_dl_COL_floor2_mesh_layer_1[];
extern Gfx hmc_dl_BALLS_002_mesh_layer_1[];
extern Gfx hmc_dl_COL_floor3_mesh_layer_1[];
extern Gfx hmc_dl_BALLS_003_mesh_layer_1[];
extern Gfx hmc_dl_COL_floor4_mesh_layer_1[];
