extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern u8 hmc_dl_mountain_fixed_i8[];
extern u8 hmc_dl_locked_banner_b_ci4[];
extern u8 hmc_dl_locked_banner_b_pal_rgba16[];
extern u8 hmc_dl_locked_banner_a_ci4[];
extern u8 hmc_dl_locked_banner_a_pal_rgba16[];
extern u8 hmc_dl_locked_banner_c_ci4[];
extern u8 hmc_dl_locked_banner_c_pal_rgba16[];
extern Vtx hmc_dl_COL_floor_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_COL_floor_mesh_layer_1_vtx_0[4];
extern Gfx hmc_dl_COL_floor_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Key_gate_mesh_layer_5_vtx_cull[8];
extern Vtx hmc_dl_Key_gate_mesh_layer_5_vtx_0[8];
extern Gfx hmc_dl_Key_gate_mesh_layer_5_tri_0[];
extern Vtx hmc_dl_Key_gate_mesh_layer_5_vtx_1[4];
extern Gfx hmc_dl_Key_gate_mesh_layer_5_tri_1[];
extern Vtx hmc_dl_Key_gate_mesh_layer_5_vtx_2[8];
extern Gfx hmc_dl_Key_gate_mesh_layer_5_tri_2[];
extern Gfx mat_hmc_dl_COL_GROUND2[];
extern Gfx mat_hmc_dl_Finish_b[];
extern Gfx mat_revert_hmc_dl_Finish_b[];
extern Gfx mat_hmc_dl_Finish_a[];
extern Gfx mat_revert_hmc_dl_Finish_a[];
extern Gfx mat_hmc_dl_Finish_c[];
extern Gfx mat_revert_hmc_dl_Finish_c[];
extern Gfx hmc_dl_COL_floor_mesh_layer_1[];
extern Gfx hmc_dl_Key_gate_mesh_layer_5[];
