extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_dl_1_area1_geo[];
extern const GeoLayout wf_dl_2_area1_geo[];
extern const GeoLayout wf_dl_3_area1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const u8 wf_area_1_collision_rooms[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_dl_1_area2_geo[];
extern const GeoLayout wf_dl_2_area2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const u8 wf_area_2_collision_rooms[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_dl_1_area3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const u8 wf_area_3_collision_rooms[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_dl_1_area4_geo[];
extern const GeoLayout wf_dl_2_area4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const u8 wf_area_4_collision_rooms[];
extern const MacroObject wf_area_4_macro_objs[];
extern u8 wf_dl_aqueduct_edge_ci8[];
extern u8 wf_dl_aqueduct_edge_pal_rgba16[];
extern u8 wf_dl_aqueduct_wall_ci8[];
extern u8 wf_dl_aqueduct_wall_pal_rgba16[];
extern u8 wf_dl_bricks_ci8[];
extern u8 wf_dl_bricks_pal_rgba16[];
extern u8 wf_dl_dirt_ci4_ci4[];
extern u8 wf_dl_dirt_ci4_x_rocks_ci4_pal_rgba16[];
extern u8 wf_dl_rocks_ci4_ci4[];
extern u8 wf_dl_dirt_3_rgba16[];
extern u8 wf_dl_dirt_1_rgba16[];
extern u8 wf_dl_grass_rgba16[];
extern u8 wf_dl_dirt_ci4_rgba16[];
extern u8 wf_dl_trees_B_ci4[];
extern u8 wf_dl_trees_B_pal_rgba16[];
extern u8 wf_dl_trees_A_ci4[];
extern u8 wf_dl_trees_A_pal_rgba16[];
extern Vtx wf_dl_A_Aqueduct_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_mesh_layer_1_vtx_1[36];
extern Gfx wf_dl_A_Aqueduct_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_mesh_layer_1_vtx_2[741];
extern Gfx wf_dl_A_Aqueduct_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_001_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_001_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_001_mesh_layer_1_vtx_1[36];
extern Gfx wf_dl_A_Aqueduct_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_001_mesh_layer_1_vtx_2[741];
extern Gfx wf_dl_A_Aqueduct_001_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_002_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_002_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_002_mesh_layer_1_vtx_1[36];
extern Gfx wf_dl_A_Aqueduct_002_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_002_mesh_layer_1_vtx_2[741];
extern Gfx wf_dl_A_Aqueduct_002_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_003_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_003_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_003_mesh_layer_1_vtx_1[40];
extern Gfx wf_dl_A_Aqueduct_003_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_003_mesh_layer_1_vtx_2[742];
extern Gfx wf_dl_A_Aqueduct_003_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Environment_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Environment_mesh_layer_1_vtx_0[287];
extern Gfx wf_dl_A_Environment_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Environment_mesh_layer_1_vtx_1[184];
extern Gfx wf_dl_A_Environment_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Environment_mesh_layer_1_vtx_2[485];
extern Gfx wf_dl_A_Environment_mesh_layer_1_tri_2[];
extern Vtx wf_dl_B_Trees_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_B_Trees_mesh_layer_4_vtx_0[144];
extern Gfx wf_dl_B_Trees_mesh_layer_4_tri_0[];
extern Vtx wf_dl_B_Trees_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_B_Trees_mesh_layer_1_vtx_0[144];
extern Gfx wf_dl_B_Trees_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_Aqueduct_a[];
extern Gfx mat_revert_wf_dl_Aqueduct_a[];
extern Gfx mat_wf_dl_Aqueduct_b[];
extern Gfx mat_revert_wf_dl_Aqueduct_b[];
extern Gfx mat_wf_dl_Bricks[];
extern Gfx mat_revert_wf_dl_Bricks[];
extern Gfx mat_wf_dl_Dirt_layer1[];
extern Gfx mat_revert_wf_dl_Dirt_layer1[];
extern Gfx mat_wf_dl_Grass_to_dirt_layer1[];
extern Gfx mat_revert_wf_dl_Grass_to_dirt_layer1[];
extern Gfx mat_wf_dl_Grass_layer1[];
extern Gfx mat_revert_wf_dl_Grass_layer1[];
extern Gfx mat_wf_dl_Trees_top[];
extern Gfx mat_revert_wf_dl_Trees_top[];
extern Gfx mat_wf_dl_Trees_bottom[];
extern Gfx mat_revert_wf_dl_Trees_bottom[];
extern Gfx wf_dl_A_Aqueduct_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_001_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_002_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_003_mesh_layer_1[];
extern Gfx wf_dl_A_Environment_mesh_layer_1[];
extern Gfx wf_dl_B_Trees_mesh_layer_4[];
extern Gfx wf_dl_B_Trees_mesh_layer_1[];
