extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_dl_1_area1_geo[];
extern const GeoLayout wf_dl_2_area1_geo[];
extern const GeoLayout wf_dl_3_area1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const u8 wf_area_1_collision_rooms[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_dl_1_area2_geo[];
extern const GeoLayout wf_dl_2_area2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const u8 wf_area_2_collision_rooms[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_dl_1_area3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const u8 wf_area_3_collision_rooms[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_dl_1_area4_geo[];
extern const GeoLayout wf_dl_2_area4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const u8 wf_area_4_collision_rooms[];
extern const MacroObject wf_area_4_macro_objs[];
extern u8 wf_dl_aqueduct_edge_ci8[];
extern u8 wf_dl_aqueduct_edge_pal_rgba16[];
extern u8 wf_dl_aqueduct_wall_ci8[];
extern u8 wf_dl_aqueduct_wall_pal_rgba16[];
extern u8 wf_dl_bricks_ci8[];
extern u8 wf_dl_bricks_pal_rgba16[];
extern u8 wf_dl_slate_i8[];
extern u8 wf_dl_aqueduct_bricks_ci8[];
extern u8 wf_dl_aqueduct_bricks_pal_rgba16[];
extern u8 wf_dl_dirt_3_rgba16[];
extern u8 wf_dl_dirt_1_rgba16[];
extern u8 wf_dl_dirt_ci4_ci4[];
extern u8 wf_dl_dirt_ci4_x_rocks_ci4_pal_rgba16[];
extern u8 wf_dl_rocks_ci4_ci4[];
extern u8 wf_dl_grass_rgba16[];
extern u8 wf_dl_dirt_ci4_rgba16[];
extern u8 wf_dl_pebble_wall_rgba16[];
extern u8 wf_dl_dirt_4_ci4[];
extern u8 wf_dl_dirt_4_x_pebble_wall_pal_rgba16[];
extern u8 wf_dl_pebble_wall_ci4[];
extern u8 wf_dl_trees_B_ci4[];
extern u8 wf_dl_trees_B_pal_rgba16[];
extern u8 wf_dl_trees_A_ci4[];
extern u8 wf_dl_trees_A_pal_rgba16[];
extern u8 wf_dl_wave_black_ia8_ia8[];
extern u8 wf_dl_black_start_ia8_ia8[];
extern u8 wf_dl_dot_black_ai8_ia8[];
extern u8 wf_dl_water_b_i4[];
extern Vtx wf_dl_A_Aqueduct_a_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_a_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_a_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_a_mesh_layer_1_vtx_1[36];
extern Gfx wf_dl_A_Aqueduct_a_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_a_mesh_layer_1_vtx_2[741];
extern Gfx wf_dl_A_Aqueduct_a_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_b_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_b_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_b_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_b_mesh_layer_1_vtx_1[36];
extern Gfx wf_dl_A_Aqueduct_b_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_b_mesh_layer_1_vtx_2[740];
extern Gfx wf_dl_A_Aqueduct_b_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_c_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_c_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_c_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_c_mesh_layer_1_vtx_1[36];
extern Gfx wf_dl_A_Aqueduct_c_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_c_mesh_layer_1_vtx_2[740];
extern Gfx wf_dl_A_Aqueduct_c_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_d_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_d_mesh_layer_1_vtx_0[60];
extern Gfx wf_dl_A_Aqueduct_d_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_d_mesh_layer_1_vtx_1[40];
extern Gfx wf_dl_A_Aqueduct_d_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_d_mesh_layer_1_vtx_2[741];
extern Gfx wf_dl_A_Aqueduct_d_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_vtx_0[88];
extern Gfx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_vtx_1[48];
extern Gfx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_vtx_2[4];
extern Gfx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_vtx_3[4];
extern Gfx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_tri_3[];
extern Vtx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_vtx_4[8];
extern Gfx wf_dl_A_Aqueduct_tower_a_mesh_layer_1_tri_4[];
extern Vtx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_vtx_0[8];
extern Gfx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_vtx_1[104];
extern Gfx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_vtx_2[72];
extern Gfx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_vtx_3[4];
extern Gfx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_tri_3[];
extern Vtx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_vtx_4[4];
extern Gfx wf_dl_A_Aqueduct_tower_b_mesh_layer_1_tri_4[];
extern Vtx wf_dl_A_Environment_a_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Environment_a_mesh_layer_1_vtx_0[195];
extern Gfx wf_dl_A_Environment_a_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Environment_a_mesh_layer_1_vtx_1[279];
extern Gfx wf_dl_A_Environment_a_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Environment_a_mesh_layer_1_vtx_2[684];
extern Gfx wf_dl_A_Environment_a_mesh_layer_1_tri_2[];
extern Vtx wf_dl_A_Environment_a_mesh_layer_1_vtx_3[214];
extern Gfx wf_dl_A_Environment_a_mesh_layer_1_tri_3[];
extern Vtx wf_dl_A_Environment_b_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Environment_b_mesh_layer_1_vtx_0[146];
extern Gfx wf_dl_A_Environment_b_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Environment_b_mesh_layer_1_vtx_1[42];
extern Gfx wf_dl_A_Environment_b_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Environment_c_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Environment_c_mesh_layer_1_vtx_0[76];
extern Gfx wf_dl_A_Environment_c_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Environment_c_mesh_layer_1_vtx_1[61];
extern Gfx wf_dl_A_Environment_c_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Environment_d_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Environment_d_mesh_layer_1_vtx_0[46];
extern Gfx wf_dl_A_Environment_d_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Environment_d_mesh_layer_1_vtx_1[108];
extern Gfx wf_dl_A_Environment_d_mesh_layer_1_tri_1[];
extern Vtx wf_dl_A_Lake_floor_a_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Lake_floor_a_mesh_layer_1_vtx_0[21];
extern Gfx wf_dl_A_Lake_floor_a_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Lake_floor_b_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Lake_floor_b_mesh_layer_1_vtx_0[50];
extern Gfx wf_dl_A_Lake_floor_b_mesh_layer_1_tri_0[];
extern Vtx wf_dl_A_Lake_floor_c_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_A_Lake_floor_c_mesh_layer_1_vtx_0[52];
extern Gfx wf_dl_A_Lake_floor_c_mesh_layer_1_tri_0[];
extern Vtx wf_dl_B_Trees_a_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_B_Trees_a_mesh_layer_4_vtx_0[64];
extern Gfx wf_dl_B_Trees_a_mesh_layer_4_tri_0[];
extern Vtx wf_dl_B_Trees_a_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_B_Trees_a_mesh_layer_1_vtx_0[64];
extern Gfx wf_dl_B_Trees_a_mesh_layer_1_tri_0[];
extern Vtx wf_dl_B_Trees_b_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_B_Trees_b_mesh_layer_4_vtx_0[78];
extern Gfx wf_dl_B_Trees_b_mesh_layer_4_tri_0[];
extern Vtx wf_dl_B_Trees_b_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_B_Trees_b_mesh_layer_1_vtx_0[78];
extern Gfx wf_dl_B_Trees_b_mesh_layer_1_tri_0[];
extern Vtx wf_dl_B_Trees_c_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_B_Trees_c_mesh_layer_4_vtx_0[38];
extern Gfx wf_dl_B_Trees_c_mesh_layer_4_tri_0[];
extern Vtx wf_dl_B_Trees_c_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_B_Trees_c_mesh_layer_1_vtx_0[38];
extern Gfx wf_dl_B_Trees_c_mesh_layer_1_tri_0[];
extern Vtx wf_dl_B_Trees_d_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_B_Trees_d_mesh_layer_4_vtx_0[14];
extern Gfx wf_dl_B_Trees_d_mesh_layer_4_tri_0[];
extern Vtx wf_dl_B_Trees_d_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_B_Trees_d_mesh_layer_1_vtx_0[14];
extern Gfx wf_dl_B_Trees_d_mesh_layer_1_tri_0[];
extern Vtx wf_dl_B_Trees_e_mesh_layer_4_vtx_cull[8];
extern Vtx wf_dl_B_Trees_e_mesh_layer_4_vtx_0[18];
extern Gfx wf_dl_B_Trees_e_mesh_layer_4_tri_0[];
extern Vtx wf_dl_B_Trees_e_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_B_Trees_e_mesh_layer_1_vtx_0[18];
extern Gfx wf_dl_B_Trees_e_mesh_layer_1_tri_0[];
extern Vtx wf_dl_C_start_line_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_C_start_line_mesh_layer_5_vtx_0[8];
extern Gfx wf_dl_C_start_line_mesh_layer_5_tri_0[];
extern Vtx wf_dl_C_start_line_mesh_layer_5_vtx_1[4];
extern Gfx wf_dl_C_start_line_mesh_layer_5_tri_1[];
extern Vtx wf_dl_C_start_line_mesh_layer_5_vtx_2[8];
extern Gfx wf_dl_C_start_line_mesh_layer_5_tri_2[];
extern Vtx wf_dl_C_water_a1_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_C_water_a1_mesh_layer_5_vtx_0[35];
extern Gfx wf_dl_C_water_a1_mesh_layer_5_tri_0[];
extern Vtx wf_dl_C_water_a2_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_C_water_a2_mesh_layer_5_vtx_0[175];
extern Gfx wf_dl_C_water_a2_mesh_layer_5_tri_0[];
extern Vtx wf_dl_C_water_b1_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_C_water_b1_mesh_layer_5_vtx_0[35];
extern Gfx wf_dl_C_water_b1_mesh_layer_5_tri_0[];
extern Vtx wf_dl_C_water_b2_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_C_water_b2_mesh_layer_5_vtx_0[175];
extern Gfx wf_dl_C_water_b2_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_Aqueduct_a[];
extern Gfx mat_revert_wf_dl_Aqueduct_a[];
extern Gfx mat_wf_dl_Aqueduct_b[];
extern Gfx mat_revert_wf_dl_Aqueduct_b[];
extern Gfx mat_wf_dl_Bricks[];
extern Gfx mat_revert_wf_dl_Bricks[];
extern Gfx mat_wf_dl_Stale[];
extern Gfx mat_wf_dl_Aqueduct_c[];
extern Gfx mat_revert_wf_dl_Aqueduct_c[];
extern Gfx mat_wf_dl_Grass_to_dirt_layer1[];
extern Gfx mat_revert_wf_dl_Grass_to_dirt_layer1[];
extern Gfx mat_wf_dl_Dirt_layer1[];
extern Gfx mat_revert_wf_dl_Dirt_layer1[];
extern Gfx mat_wf_dl_Grass_layer1[];
extern Gfx mat_revert_wf_dl_Grass_layer1[];
extern Gfx mat_wf_dl_Grass_to_dirt2_layer1[];
extern Gfx mat_revert_wf_dl_Grass_to_dirt2_layer1[];
extern Gfx mat_wf_dl_Dirt_to_pebble_layer1[];
extern Gfx mat_revert_wf_dl_Dirt_to_pebble_layer1[];
extern Gfx mat_wf_dl_Trees_top[];
extern Gfx mat_revert_wf_dl_Trees_top[];
extern Gfx mat_wf_dl_Trees_bottom[];
extern Gfx mat_revert_wf_dl_Trees_bottom[];
extern Gfx mat_wf_dl_Finish_b[];
extern Gfx mat_revert_wf_dl_Finish_b[];
extern Gfx mat_wf_dl_Start[];
extern Gfx mat_revert_wf_dl_Start[];
extern Gfx mat_wf_dl_Finish_c[];
extern Gfx mat_revert_wf_dl_Finish_c[];
extern Gfx mat_wf_dl_Flow_a_layer5[];
extern Gfx mat_revert_wf_dl_Flow_a_layer5[];
extern Gfx mat_wf_dl_Flow_b_layer5[];
extern Gfx mat_revert_wf_dl_Flow_b_layer5[];
extern Gfx wf_dl_A_Aqueduct_a_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_b_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_c_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_d_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_tower_a_mesh_layer_1[];
extern Gfx wf_dl_A_Aqueduct_tower_b_mesh_layer_1[];
extern Gfx wf_dl_A_Environment_a_mesh_layer_1[];
extern Gfx wf_dl_A_Environment_b_mesh_layer_1[];
extern Gfx wf_dl_A_Environment_c_mesh_layer_1[];
extern Gfx wf_dl_A_Environment_d_mesh_layer_1[];
extern Gfx wf_dl_A_Lake_floor_a_mesh_layer_1[];
extern Gfx wf_dl_A_Lake_floor_b_mesh_layer_1[];
extern Gfx wf_dl_A_Lake_floor_c_mesh_layer_1[];
extern Gfx wf_dl_B_Trees_a_mesh_layer_4[];
extern Gfx wf_dl_B_Trees_a_mesh_layer_1[];
extern Gfx wf_dl_B_Trees_b_mesh_layer_4[];
extern Gfx wf_dl_B_Trees_b_mesh_layer_1[];
extern Gfx wf_dl_B_Trees_c_mesh_layer_4[];
extern Gfx wf_dl_B_Trees_c_mesh_layer_1[];
extern Gfx wf_dl_B_Trees_d_mesh_layer_4[];
extern Gfx wf_dl_B_Trees_d_mesh_layer_1[];
extern Gfx wf_dl_B_Trees_e_mesh_layer_4[];
extern Gfx wf_dl_B_Trees_e_mesh_layer_1[];
extern Gfx wf_dl_C_start_line_mesh_layer_5[];
extern Gfx wf_dl_C_water_a1_mesh_layer_5[];
extern Gfx wf_dl_C_water_a2_mesh_layer_5[];
extern Gfx wf_dl_C_water_b1_mesh_layer_5[];
extern Gfx wf_dl_C_water_b2_mesh_layer_5[];
