extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_dl_1_area1_geo[];
extern const GeoLayout jrb_dl_2_area1_geo[];
extern const GeoLayout jrb_dl_3_area1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const u8 jrb_area_1_collision_rooms[];
extern const MacroObject jrb_area_1_macro_objs[];
extern const GeoLayout jrb_area_2_geo[];
extern const GeoLayout jrb_dl_1_area2_geo[];
extern const GeoLayout jrb_dl_2_area2_geo[];
extern const GeoLayout jrb_area_2[];
extern const Collision jrb_area_2_collision[];
extern const u8 jrb_area_2_collision_rooms[];
extern const MacroObject jrb_area_2_macro_objs[];
extern const GeoLayout jrb_area_3_geo[];
extern const GeoLayout jrb_dl_1_area3_geo[];
extern const GeoLayout jrb_area_3[];
extern const Collision jrb_area_3_collision[];
extern const u8 jrb_area_3_collision_rooms[];
extern const MacroObject jrb_area_3_macro_objs[];
extern u8 jrb_dl_dirt_7_rgba16[];
extern u8 jrb_dl_c3_rocks_combi_ci8[];
extern u8 jrb_dl_c3_rocks_combi_pal_rgba16[];
extern u8 jrb_dl_grass2_rgba16[];
extern u8 jrb_dl_dirt_5_rgba16[];
extern u8 jrb_dl_dirt_6_rgba16[];
extern u8 jrb_dl_c3_rocks_combi_rgba16[];
extern u8 jrb_dl_bridge_ci8[];
extern u8 jrb_dl_bridge_pal_rgba16[];
extern u8 jrb_dl_wave_white_ia8_ia8[];
extern u8 jrb_dl_white_start_ia8_ia8[];
extern u8 jrb_dl_dot_white_ai8_ia8[];
extern u8 jrb_dl_white_finish_ia8_ia8[];
extern Vtx jrb_dl_A_environment_a1_a_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_A_environment_a1_a_mesh_layer_1_vtx_0[69];
extern Gfx jrb_dl_A_environment_a1_a_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_A_environment_a1_a_mesh_layer_1_vtx_1[379];
extern Gfx jrb_dl_A_environment_a1_a_mesh_layer_1_tri_1[];
extern Vtx jrb_dl_A_environment_a1_a_mesh_layer_1_vtx_2[282];
extern Gfx jrb_dl_A_environment_a1_a_mesh_layer_1_tri_2[];
extern Vtx jrb_dl_A_environment_a1_a_mesh_layer_1_vtx_3[357];
extern Gfx jrb_dl_A_environment_a1_a_mesh_layer_1_tri_3[];
extern Vtx jrb_dl_A_environment_a1_b_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_A_environment_a1_b_mesh_layer_1_vtx_0[325];
extern Gfx jrb_dl_A_environment_a1_b_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_A_environment_a1_c_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_A_environment_a1_c_mesh_layer_1_vtx_0[988];
extern Gfx jrb_dl_A_environment_a1_c_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_A_environment_a1_d_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_A_environment_a1_d_mesh_layer_1_vtx_0[1083];
extern Gfx jrb_dl_A_environment_a1_d_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Bridge_a_mesh_layer_4_vtx_cull[8];
extern Vtx jrb_dl_Bridge_a_mesh_layer_4_vtx_0[12];
extern Gfx jrb_dl_Bridge_a_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_Bridge_b_mesh_layer_4_vtx_cull[8];
extern Vtx jrb_dl_Bridge_b_mesh_layer_4_vtx_0[14];
extern Gfx jrb_dl_Bridge_b_mesh_layer_4_tri_0[];
extern Vtx jrb_dl_C_sart_line_mesh_layer_5_vtx_cull[8];
extern Vtx jrb_dl_C_sart_line_mesh_layer_5_vtx_0[8];
extern Gfx jrb_dl_C_sart_line_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_C_sart_line_mesh_layer_5_vtx_1[4];
extern Gfx jrb_dl_C_sart_line_mesh_layer_5_tri_1[];
extern Vtx jrb_dl_C_sart_line_mesh_layer_5_vtx_2[8];
extern Gfx jrb_dl_C_sart_line_mesh_layer_5_tri_2[];
extern Vtx jrb_dl_C_Finish_line_mesh_layer_5_vtx_cull[8];
extern Vtx jrb_dl_C_Finish_line_mesh_layer_5_vtx_0[96];
extern Gfx jrb_dl_C_Finish_line_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_C_Finish_line_mesh_layer_5_vtx_1[96];
extern Gfx jrb_dl_C_Finish_line_mesh_layer_5_tri_1[];
extern Vtx jrb_dl_C_Finish_line_mesh_layer_5_vtx_2[36];
extern Gfx jrb_dl_C_Finish_line_mesh_layer_5_tri_2[];
extern Gfx mat_jrb_dl_Dirt[];
extern Gfx mat_jrb_dl_Rock[];
extern Gfx mat_revert_jrb_dl_Rock[];
extern Gfx mat_jrb_dl_Grass_layer1[];
extern Gfx mat_revert_jrb_dl_Grass_layer1[];
extern Gfx mat_jrb_dl_Grass_to_rock_layer1[];
extern Gfx mat_revert_jrb_dl_Grass_to_rock_layer1[];
extern Gfx mat_jrb_dl_Bridge[];
extern Gfx mat_revert_jrb_dl_Bridge[];
extern Gfx mat_jrb_dl_Finish_b[];
extern Gfx mat_revert_jrb_dl_Finish_b[];
extern Gfx mat_jrb_dl_Start[];
extern Gfx mat_revert_jrb_dl_Start[];
extern Gfx mat_jrb_dl_Finish_c[];
extern Gfx mat_revert_jrb_dl_Finish_c[];
extern Gfx mat_jrb_dl_Finish_a[];
extern Gfx mat_revert_jrb_dl_Finish_a[];
extern Gfx jrb_dl_A_environment_a1_a_mesh_layer_1[];
extern Gfx jrb_dl_A_environment_a1_b_mesh_layer_1[];
extern Gfx jrb_dl_A_environment_a1_c_mesh_layer_1[];
extern Gfx jrb_dl_A_environment_a1_d_mesh_layer_1[];
extern Gfx jrb_dl_Bridge_a_mesh_layer_4[];
extern Gfx jrb_dl_Bridge_b_mesh_layer_4[];
extern Gfx jrb_dl_C_sart_line_mesh_layer_5[];
extern Gfx jrb_dl_C_Finish_line_mesh_layer_5[];
