#include "levels/bbh/area_1/geo.inc.c"
#include "levels/bbh/area_2/geo.inc.c"
#include "levels/bbh/area_3/geo.inc.c"
#include "levels/bbh/area_4/geo.inc.c"
#include "levels/bbh/area_5/geo.inc.c"
#include "levels/bbh/area_6/geo.inc.c"
