const GeoLayout title_screen_balloon_geo[] = {
	GEO_SWITCH_CASE(7, geo_switch_bparam2),
	GEO_OPEN_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_1_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_1_mesh_layer_5),
		GEO_CLOSE_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_2_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_2_mesh_layer_5),
		GEO_CLOSE_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_3_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_3_mesh_layer_5),
		GEO_CLOSE_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_4_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_4_mesh_layer_5),
		GEO_CLOSE_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_5_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_5_mesh_layer_5),
		GEO_CLOSE_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_6_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_6_mesh_layer_5),
		GEO_CLOSE_NODE(),
        GEO_NODE_START(),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_Balloon_7_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, castle_courtyard_dl_Balloon_7_mesh_layer_5),
		GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
	GEO_END(),
};
