#include "dma_data.h"

#include "course1.c.in"
#include "course2.c.in"
#include "course3.c.in"
#include "course4.c.in"
#include "course5.c.in"
#include "course6.c.in"
#include "course7.c.in"
#include "course8.c.in"
#include "course9.c.in"
