extern const GeoLayout key_gate_Armature_switch[];
extern const GeoLayout key_gate_geo[];
extern u8 key_gate_locked_banner_b_ia16[];
extern u8 key_gate_locked_banner_a_bottom_ia16[];
extern u8 key_gate_locked_banner_c_ia16[];
extern u8 key_gate_locked_banner_a_top_ia16[];
extern Vtx key_gate_switch_child_mesh_layer_5_vtx_0[8];
extern Gfx key_gate_switch_child_mesh_layer_5_tri_0[];
extern Vtx key_gate_switch_child_mesh_layer_5_vtx_1[4];
extern Gfx key_gate_switch_child_mesh_layer_5_tri_1[];
extern Vtx key_gate_switch_child_mesh_layer_5_vtx_2[8];
extern Gfx key_gate_switch_child_mesh_layer_5_tri_2[];
extern Vtx key_gate_switch_child_mesh_layer_5_vtx_3[4];
extern Gfx key_gate_switch_child_mesh_layer_5_tri_3[];
extern Gfx mat_key_gate_Locked_waves[];
extern Gfx mat_revert_key_gate_Locked_waves[];
extern Gfx mat_key_gate_Locked_bottom[];
extern Gfx mat_revert_key_gate_Locked_bottom[];
extern Gfx mat_key_gate_Locked_dots[];
extern Gfx mat_revert_key_gate_Locked_dots[];
extern Gfx mat_key_gate_Locked_top[];
extern Gfx mat_revert_key_gate_Locked_top[];
extern Gfx key_gate_switch_child_mesh_layer_5[];
