#include "levels/ddd/area_1/geo.inc.c"
#include "levels/ddd/area_2/geo.inc.c"
#include "levels/ddd/area_3/geo.inc.c"
#include "levels/ddd/area_4/geo.inc.c"
#include "levels/ddd/area_5/geo.inc.c"
#include "levels/ddd/area_6/geo.inc.c"
#include "levels/ddd/area_7/geo.inc.c"
#include "levels/ddd/area_8/geo.inc.c"
