extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_dl_1_area1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const u8 ddd_area_1_collision_rooms[];
extern const MacroObject ddd_area_1_macro_objs[];
extern const GeoLayout ddd_area_2_geo[];
extern const GeoLayout ddd_dl_1_area2_geo[];
extern const GeoLayout ddd_dl_2_area2_geo[];
extern const GeoLayout ddd_area_2[];
extern const Collision ddd_area_2_collision[];
extern const u8 ddd_area_2_collision_rooms[];
extern const MacroObject ddd_area_2_macro_objs[];
extern const GeoLayout ddd_area_3_geo[];
extern const GeoLayout ddd_dl_1_area3_geo[];
extern const GeoLayout ddd_dl_2_area_3_geo[];
extern const GeoLayout ddd_area_3[];
extern const Collision ddd_area_3_collision[];
extern const u8 ddd_area_3_collision_rooms[];
extern const MacroObject ddd_area_3_macro_objs[];
extern const GeoLayout ddd_area_4_geo[];
extern const GeoLayout ddd_dl_1_area4_geo[];
extern const GeoLayout ddd_dl_2_area4_geo[];
extern const GeoLayout ddd_dl_3_area4_geo[];
extern const GeoLayout ddd_area_4[];
extern const Collision ddd_area_4_collision[];
extern const u8 ddd_area_4_collision_rooms[];
extern const MacroObject ddd_area_4_macro_objs[];
extern const GeoLayout ddd_area_5_geo[];
extern const GeoLayout ddd_dl_1_area5_geo[];
extern const GeoLayout ddd_dl_2_area5_geo[];
extern const GeoLayout ddd_dl_3_area5_geo[];
extern const GeoLayout ddd_area_5[];
extern const Collision ddd_area_5_collision[];
extern const u8 ddd_area_5_collision_rooms[];
extern const MacroObject ddd_area_5_macro_objs[];
extern const GeoLayout ddd_area_6_geo[];
extern const GeoLayout ddd_dl_1_area6_geo[];
extern const GeoLayout ddd_area_6[];
extern const Collision ddd_area_6_collision[];
extern const u8 ddd_area_6_collision_rooms[];
extern const MacroObject ddd_area_6_macro_objs[];
extern u8 ddd_dl_night_sky_2_ci8[];
extern u8 ddd_dl_night_sky_2_pal_rgba16[];
extern u8 ddd_dl_snow_sparkles_ci4[];
extern u8 ddd_dl_snow_sparkles_pal_rgba16[];
extern u8 ddd_dl_sun_glow_ia16[];
extern u8 ddd_dl_Moon_ia8[];
extern u8 ddd_dl_dot_white_ai8_ia8[];
extern u8 ddd_dl_wave_white_ia8_ia8[];
extern u8 ddd_dl_white_start_ia8_ia8[];
extern u8 ddd_dl_gold_foil_ci8[];
extern u8 ddd_dl_gold_foil_pal_rgba16[];
extern u8 ddd_dl_Glass_4_rgba32[];
extern u8 ddd_dl_dot_lights_ia8[];
extern u8 ddd_dl_purple_foil_ci8[];
extern u8 ddd_dl_purple_foil_pal_rgba16[];
extern u8 ddd_dl_rainbow_ci8[];
extern u8 ddd_dl_rainbow_pal_rgba16[];
extern u8 ddd_dl_glass_star_tiles_ia8[];
extern Vtx ddd_dl_0_skybox_a_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_0_skybox_a_mesh_layer_1_vtx_0[87];
extern Gfx ddd_dl_0_skybox_a_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_0_skybox_b_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_0_skybox_b_mesh_layer_1_vtx_0[87];
extern Gfx ddd_dl_0_skybox_b_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_0_skybox_c_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_0_skybox_c_mesh_layer_1_vtx_0[87];
extern Gfx ddd_dl_0_skybox_c_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_0_skybox_d_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_0_skybox_d_mesh_layer_1_vtx_0[87];
extern Gfx ddd_dl_0_skybox_d_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_0_stars_mesh_layer_4_vtx_cull[8];
extern Vtx ddd_dl_0_stars_mesh_layer_4_vtx_0[56];
extern Gfx ddd_dl_0_stars_mesh_layer_4_tri_0[];
extern Vtx ddd_dl_0_stars_001_mesh_layer_4_vtx_cull[8];
extern Vtx ddd_dl_0_stars_001_mesh_layer_4_vtx_0[48];
extern Gfx ddd_dl_0_stars_001_mesh_layer_4_tri_0[];
extern Vtx ddd_dl_0_stars_002_mesh_layer_4_vtx_cull[8];
extern Vtx ddd_dl_0_stars_002_mesh_layer_4_vtx_0[56];
extern Gfx ddd_dl_0_stars_002_mesh_layer_4_tri_0[];
extern Vtx ddd_dl_0_stars_003_mesh_layer_4_vtx_cull[8];
extern Vtx ddd_dl_0_stars_003_mesh_layer_4_vtx_0[62];
extern Gfx ddd_dl_0_stars_003_mesh_layer_4_tri_0[];
extern Vtx ddd_dl_A_moon_glow_mesh_layer_5_vtx_cull[8];
extern Vtx ddd_dl_A_moon_glow_mesh_layer_5_vtx_0[4];
extern Gfx ddd_dl_A_moon_glow_mesh_layer_5_tri_0[];
extern Vtx ddd_dl_A_the_fucking_moon_mesh_layer_4_vtx_cull[8];
extern Vtx ddd_dl_A_the_fucking_moon_mesh_layer_4_vtx_0[4];
extern Gfx ddd_dl_A_the_fucking_moon_mesh_layer_4_tri_0[];
extern Vtx ddd_dl_C_start_line_mesh_layer_5_vtx_cull[8];
extern Vtx ddd_dl_C_start_line_mesh_layer_5_vtx_0[24];
extern Gfx ddd_dl_C_start_line_mesh_layer_5_tri_0[];
extern Vtx ddd_dl_C_start_line_mesh_layer_5_vtx_1[24];
extern Gfx ddd_dl_C_start_line_mesh_layer_5_tri_1[];
extern Vtx ddd_dl_C_start_line_mesh_layer_5_vtx_2[10];
extern Gfx ddd_dl_C_start_line_mesh_layer_5_tri_2[];
extern Vtx ddd_dl_golden_TCS_emblem_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_golden_TCS_emblem_mesh_layer_1_vtx_0[1014];
extern Gfx ddd_dl_golden_TCS_emblem_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_golden_TCS_emblem_mesh_layer_1_vtx_1[64];
extern Gfx ddd_dl_golden_TCS_emblem_mesh_layer_1_tri_1[];
extern Vtx ddd_dl_golden_TCS_emblem_mesh_layer_5_vtx_cull[8];
extern Vtx ddd_dl_golden_TCS_emblem_mesh_layer_5_vtx_0[4];
extern Gfx ddd_dl_golden_TCS_emblem_mesh_layer_5_tri_0[];
extern Vtx ddd_dl_golden_TCS_emblem_mesh_layer_5_vtx_1[704];
extern Gfx ddd_dl_golden_TCS_emblem_mesh_layer_5_tri_1[];
extern Vtx ddd_dl_stage_a1_mesh_layer_5_vtx_cull[8];
extern Vtx ddd_dl_stage_a1_mesh_layer_5_vtx_0[24];
extern Gfx ddd_dl_stage_a1_mesh_layer_5_tri_0[];
extern Vtx ddd_dl_stage_a1_mesh_layer_5_vtx_1[12];
extern Gfx ddd_dl_stage_a1_mesh_layer_5_tri_1[];
extern Vtx ddd_dl_stage_a1_mesh_layer_5_vtx_2[54];
extern Gfx ddd_dl_stage_a1_mesh_layer_5_tri_2[];
extern Gfx mat_ddd_dl_night_sky[];
extern Gfx mat_revert_ddd_dl_night_sky[];
extern Gfx mat_ddd_dl_Stars_001[];
extern Gfx mat_revert_ddd_dl_Stars_001[];
extern Gfx mat_ddd_dl_Glow_001[];
extern Gfx mat_revert_ddd_dl_Glow_001[];
extern Gfx mat_ddd_dl_the_fucking_moon[];
extern Gfx mat_revert_ddd_dl_the_fucking_moon[];
extern Gfx mat_ddd_dl_Finish_c[];
extern Gfx mat_revert_ddd_dl_Finish_c[];
extern Gfx mat_ddd_dl_Finish_b[];
extern Gfx mat_revert_ddd_dl_Finish_b[];
extern Gfx mat_ddd_dl_Start[];
extern Gfx mat_revert_ddd_dl_Start[];
extern Gfx mat_ddd_dl_Metal_gold[];
extern Gfx mat_revert_ddd_dl_Metal_gold[];
extern Gfx mat_ddd_dl_Glass[];
extern Gfx mat_revert_ddd_dl_Glass[];
extern Gfx mat_ddd_dl_Dot_lights[];
extern Gfx mat_revert_ddd_dl_Dot_lights[];
extern Gfx mat_ddd_dl_Metal_purple[];
extern Gfx mat_revert_ddd_dl_Metal_purple[];
extern Gfx mat_ddd_dl_Rainbow_path[];
extern Gfx mat_revert_ddd_dl_Rainbow_path[];
extern Gfx mat_ddd_dl_Glass_tile[];
extern Gfx mat_revert_ddd_dl_Glass_tile[];
extern Gfx ddd_dl_0_skybox_a_mesh_layer_1[];
extern Gfx ddd_dl_0_skybox_b_mesh_layer_1[];
extern Gfx ddd_dl_0_skybox_c_mesh_layer_1[];
extern Gfx ddd_dl_0_skybox_d_mesh_layer_1[];
extern Gfx ddd_dl_0_stars_mesh_layer_4[];
extern Gfx ddd_dl_0_stars_001_mesh_layer_4[];
extern Gfx ddd_dl_0_stars_002_mesh_layer_4[];
extern Gfx ddd_dl_0_stars_003_mesh_layer_4[];
extern Gfx ddd_dl_A_moon_glow_mesh_layer_5[];
extern Gfx ddd_dl_A_the_fucking_moon_mesh_layer_4[];
extern Gfx ddd_dl_C_start_line_mesh_layer_5[];
extern Gfx ddd_dl_golden_TCS_emblem_mesh_layer_1[];
extern Gfx ddd_dl_golden_TCS_emblem_mesh_layer_5[];
extern Gfx ddd_dl_stage_a1_mesh_layer_5[];
